//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.18 at 08:39:32 PM CEST 
//


package com.megatravel.korisniciservice.soap.dto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.megatravel.korisniciservice.soap.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.megatravel.korisniciservice.soap.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAgentLoginResponse }
     * 
     */
    public GetAgentLoginResponse createGetAgentLoginResponse() {
        return new GetAgentLoginResponse();
    }

    /**
     * Create an instance of {@link AgentDTO }
     * 
     */
    public AgentDTO createAgentDTO() {
        return new AgentDTO();
    }

    /**
     * Create an instance of {@link GetSviSpojeviAgentSmestajResponse }
     * 
     */
    public GetSviSpojeviAgentSmestajResponse createGetSviSpojeviAgentSmestajResponse() {
        return new GetSviSpojeviAgentSmestajResponse();
    }

    /**
     * Create an instance of {@link SpojAgentSmestajDTO }
     * 
     */
    public SpojAgentSmestajDTO createSpojAgentSmestajDTO() {
        return new SpojAgentSmestajDTO();
    }

    /**
     * Create an instance of {@link GetSviKorisniciRequest }
     * 
     */
    public GetSviKorisniciRequest createGetSviKorisniciRequest() {
        return new GetSviKorisniciRequest();
    }

    /**
     * Create an instance of {@link GetSviKorisniciResponse }
     * 
     */
    public GetSviKorisniciResponse createGetSviKorisniciResponse() {
        return new GetSviKorisniciResponse();
    }

    /**
     * Create an instance of {@link KorisnikDTO }
     * 
     */
    public KorisnikDTO createKorisnikDTO() {
        return new KorisnikDTO();
    }

    /**
     * Create an instance of {@link GetSviAgentiRequest }
     * 
     */
    public GetSviAgentiRequest createGetSviAgentiRequest() {
        return new GetSviAgentiRequest();
    }

    /**
     * Create an instance of {@link GetSviSpojeviAgentSmestajRequest }
     * 
     */
    public GetSviSpojeviAgentSmestajRequest createGetSviSpojeviAgentSmestajRequest() {
        return new GetSviSpojeviAgentSmestajRequest();
    }

    /**
     * Create an instance of {@link GetSviAgentiResponse }
     * 
     */
    public GetSviAgentiResponse createGetSviAgentiResponse() {
        return new GetSviAgentiResponse();
    }

    /**
     * Create an instance of {@link GetAgentLoginRequest }
     * 
     */
    public GetAgentLoginRequest createGetAgentLoginRequest() {
        return new GetAgentLoginRequest();
    }

}
