//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.19 at 11:06:20 AM CEST 
//


package com.megatravel.smestajservice.soap.dto;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.megatravel.smestajservice.model.Adresa;


/**
 * <p>Java class for AdresaDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdresaDTO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="zemlja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="grad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="geografskaDuzina" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="geografskaSirina" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdresaDTO", propOrder = {
    "id",
    "zemlja",
    "grad",
    "geografskaDuzina",
    "geografskaSirina"
})
public class AdresaDTO {

    protected long id;
    @XmlElement(required = true)
    protected String zemlja;
    @XmlElement(required = true)
    protected String grad;
    protected double geografskaDuzina;
    protected double geografskaSirina;

	public AdresaDTO() { }
	
	public AdresaDTO(Adresa adresa) {
		this.id = adresa.getId();
		this.zemlja = adresa.getZemlja();
		this.grad = adresa.getGrad();
		this.geografskaDuzina = adresa.getGeografskaDuzina();
		this.geografskaSirina = adresa.getGeografskaSirina();
	}
    
    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the zemlja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZemlja() {
        return zemlja;
    }

    /**
     * Sets the value of the zemlja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZemlja(String value) {
        this.zemlja = value;
    }

    /**
     * Gets the value of the grad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrad() {
        return grad;
    }

    /**
     * Sets the value of the grad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrad(String value) {
        this.grad = value;
    }

    /**
     * Gets the value of the geografskaDuzina property.
     * 
     */
    public double getGeografskaDuzina() {
        return geografskaDuzina;
    }

    /**
     * Sets the value of the geografskaDuzina property.
     * 
     */
    public void setGeografskaDuzina(double value) {
        this.geografskaDuzina = value;
    }

    /**
     * Gets the value of the geografskaSirina property.
     * 
     */
    public double getGeografskaSirina() {
        return geografskaSirina;
    }

    /**
     * Sets the value of the geografskaSirina property.
     * 
     */
    public void setGeografskaSirina(double value) {
        this.geografskaSirina = value;
    }

	public static List<AdresaDTO> transformisi(List<Adresa> adrese) {
		List<AdresaDTO> rezultat = new ArrayList<AdresaDTO>();
		for(Adresa adresa : adrese) {
			rezultat.add(new AdresaDTO(adresa));
		}
		return rezultat;
	}

}
