//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.19 at 11:06:20 AM CEST 
//


package com.megatravel.smestajservice.soap.dto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.megatravel.smestajservice.soap.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.megatravel.smestajservice.soap.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetSveAdreseResponse }
     * 
     */
    public GetSveAdreseResponse createGetSveAdreseResponse() {
        return new GetSveAdreseResponse();
    }

    /**
     * Create an instance of {@link AdresaDTO }
     * 
     */
    public AdresaDTO createAdresaDTO() {
        return new AdresaDTO();
    }

    /**
     * Create an instance of {@link GetSveAdreseRequest }
     * 
     */
    public GetSveAdreseRequest createGetSveAdreseRequest() {
        return new GetSveAdreseRequest();
    }

    /**
     * Create an instance of {@link GetSviCenovniciResponse }
     * 
     */
    public GetSviCenovniciResponse createGetSviCenovniciResponse() {
        return new GetSviCenovniciResponse();
    }

    /**
     * Create an instance of {@link CenovnikDTO }
     * 
     */
    public CenovnikDTO createCenovnikDTO() {
        return new CenovnikDTO();
    }

    /**
     * Create an instance of {@link GetSveSmestajneJediniceRequest }
     * 
     */
    public GetSveSmestajneJediniceRequest createGetSveSmestajneJediniceRequest() {
        return new GetSveSmestajneJediniceRequest();
    }

    /**
     * Create an instance of {@link DodavanjeSmestajneJediniceRequest }
     * 
     */
    public DodavanjeSmestajneJediniceRequest createDodavanjeSmestajneJediniceRequest() {
        return new DodavanjeSmestajneJediniceRequest();
    }

    /**
     * Create an instance of {@link SmestajnaJedinicaDTO }
     * 
     */
    public SmestajnaJedinicaDTO createSmestajnaJedinicaDTO() {
        return new SmestajnaJedinicaDTO();
    }

    /**
     * Create an instance of {@link GetSviTipoviRequest }
     * 
     */
    public GetSviTipoviRequest createGetSviTipoviRequest() {
        return new GetSviTipoviRequest();
    }

    /**
     * Create an instance of {@link UnesiRezervacijuRequest }
     * 
     */
    public UnesiRezervacijuRequest createUnesiRezervacijuRequest() {
        return new UnesiRezervacijuRequest();
    }

    /**
     * Create an instance of {@link RezervacijaDTO }
     * 
     */
    public RezervacijaDTO createRezervacijaDTO() {
        return new RezervacijaDTO();
    }

    /**
     * Create an instance of {@link PotvrdiRezervacijuRequest }
     * 
     */
    public PotvrdiRezervacijuRequest createPotvrdiRezervacijuRequest() {
        return new PotvrdiRezervacijuRequest();
    }

    /**
     * Create an instance of {@link GetSviCenovniciRequest }
     * 
     */
    public GetSviCenovniciRequest createGetSviCenovniciRequest() {
        return new GetSviCenovniciRequest();
    }

    /**
     * Create an instance of {@link GetSveSmestajneJediniceResponse }
     * 
     */
    public GetSveSmestajneJediniceResponse createGetSveSmestajneJediniceResponse() {
        return new GetSveSmestajneJediniceResponse();
    }

    /**
     * Create an instance of {@link GetSveUslugeResponse }
     * 
     */
    public GetSveUslugeResponse createGetSveUslugeResponse() {
        return new GetSveUslugeResponse();
    }

    /**
     * Create an instance of {@link UslugaDTO }
     * 
     */
    public UslugaDTO createUslugaDTO() {
        return new UslugaDTO();
    }

    /**
     * Create an instance of {@link GetSviTipoviResponse }
     * 
     */
    public GetSviTipoviResponse createGetSviTipoviResponse() {
        return new GetSviTipoviResponse();
    }

    /**
     * Create an instance of {@link TipSmestajaDTO }
     * 
     */
    public TipSmestajaDTO createTipSmestajaDTO() {
        return new TipSmestajaDTO();
    }

    /**
     * Create an instance of {@link GetSveRezervacijeResponse }
     * 
     */
    public GetSveRezervacijeResponse createGetSveRezervacijeResponse() {
        return new GetSveRezervacijeResponse();
    }

    /**
     * Create an instance of {@link GetSveUslugeRequest }
     * 
     */
    public GetSveUslugeRequest createGetSveUslugeRequest() {
        return new GetSveUslugeRequest();
    }

    /**
     * Create an instance of {@link GetSveRezervacijeRequest }
     * 
     */
    public GetSveRezervacijeRequest createGetSveRezervacijeRequest() {
        return new GetSveRezervacijeRequest();
    }

}
