//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.19 at 11:06:20 AM CEST 
//


package com.megatravel.smestajservice.soap.dto;

import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;

import com.megatravel.smestajservice.model.Rezervacija;


/**
 * <p>Java class for RezervacijaDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RezervacijaDTO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ukupnaCena" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="utisak" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="korisnik" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="realizovana" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="prviDanRezervacije" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="poslednjiDanRezervacije" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="smestaj" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RezervacijaDTO", propOrder = {
    "id",
    "ukupnaCena",
    "utisak",
    "korisnik",
    "realizovana",
    "prviDanRezervacije",
    "poslednjiDanRezervacije",
    "smestaj"
})
public class RezervacijaDTO {

    protected long id;
    protected double ukupnaCena;
    protected long utisak;
    protected long korisnik;
    protected boolean realizovana;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar prviDanRezervacije;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar poslednjiDanRezervacije;
    protected long smestaj;

    public RezervacijaDTO() { }
    
    public RezervacijaDTO(Rezervacija rezervacija) {
    	this.id = rezervacija.getId();
    	this.ukupnaCena = rezervacija.getUkupnaCena();
    	GregorianCalendar kalendar = new GregorianCalendar();
    	kalendar.setTime(Date.from(rezervacija.getPrviDanRezervacije().atStartOfDay(ZoneId.systemDefault()).toInstant()));
    	try {
			this.prviDanRezervacije = DatatypeFactory.newInstance().newXMLGregorianCalendar(kalendar);
		} catch (DatatypeConfigurationException e) {
			e.printStackTrace();
		}
    	kalendar.setTime(Date.from(rezervacija.getPoslednjiDanRezervacije().atStartOfDay(ZoneId.systemDefault()).toInstant()));
    	try {
			this.poslednjiDanRezervacije = DatatypeFactory.newInstance().newXMLGregorianCalendar(kalendar);
		} catch (DatatypeConfigurationException e) {
			e.printStackTrace();
		}
    	if(rezervacija.getUtisakId() != null) this.utisak = rezervacija.getUtisakId();
    	if(rezervacija.getKorisnikId() != null) this.korisnik = rezervacija.getKorisnikId();
    	this.realizovana = rezervacija.isRealizovana();
    	this.smestaj = rezervacija.getSmestajnaJedinica().getId();
    }
    
    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the ukupnaCena property.
     * 
     */
    public double getUkupnaCena() {
        return ukupnaCena;
    }

    /**
     * Sets the value of the ukupnaCena property.
     * 
     */
    public void setUkupnaCena(double value) {
        this.ukupnaCena = value;
    }

    /**
     * Gets the value of the utisak property.
     * 
     */
    public long getUtisak() {
        return utisak;
    }

    /**
     * Sets the value of the utisak property.
     * 
     */
    public void setUtisak(long value) {
        this.utisak = value;
    }

    /**
     * Gets the value of the korisnik property.
     * 
     */
    public long getKorisnik() {
        return korisnik;
    }

    /**
     * Sets the value of the korisnik property.
     * 
     */
    public void setKorisnik(long value) {
        this.korisnik = value;
    }

    /**
     * Gets the value of the realizovana property.
     * 
     */
    public boolean isRealizovana() {
        return realizovana;
    }

    /**
     * Sets the value of the realizovana property.
     * 
     */
    public void setRealizovana(boolean value) {
        this.realizovana = value;
    }

    /**
     * Gets the value of the prviDanRezervacije property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPrviDanRezervacije() {
        return prviDanRezervacije;
    }

    /**
     * Sets the value of the prviDanRezervacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPrviDanRezervacije(XMLGregorianCalendar value) {
        this.prviDanRezervacije = value;
    }

    /**
     * Gets the value of the poslednjiDanRezervacije property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPoslednjiDanRezervacije() {
        return poslednjiDanRezervacije;
    }

    /**
     * Sets the value of the poslednjiDanRezervacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPoslednjiDanRezervacije(XMLGregorianCalendar value) {
        this.poslednjiDanRezervacije = value;
    }

    /**
     * Gets the value of the smestaj property.
     * 
     */
    public long getSmestaj() {
        return smestaj;
    }

    /**
     * Sets the value of the smestaj property.
     * 
     */
    public void setSmestaj(long value) {
        this.smestaj = value;
    }

	public static List<RezervacijaDTO> transformisi(List<Rezervacija> rezervacije) {
		List<RezervacijaDTO> rezultat = new ArrayList<>();
		for(Rezervacija rezervacija : rezervacije) {
			rezultat.add(new RezervacijaDTO(rezervacija));
		}
		return rezultat;
	}

}
