//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.megatravel.porukeservice.soap.dto;

import java.util.ArrayList;
import java.util.Collection;
import java.util.GregorianCalendar;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;

import com.megatravel.porukeservice.model.Poruka;


/**
 * <p>Java class for PorukaDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PorukaDTO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="vreme" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="sadrzaj" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="korisnikId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="agentId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PorukaDTO", propOrder = {
    "id",
    "vreme",
    "sadrzaj",
    "korisnikId",
    "agentId"
})
public class PorukaDTO {

    protected long id;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar vreme;
    @XmlElement(required = true)
    protected String sadrzaj;
    protected long korisnikId;
    protected long agentId;

    public PorukaDTO() { }
    
    public PorukaDTO(Poruka poruka) {
    	this.id = poruka.getId();
    	GregorianCalendar kalendar = new GregorianCalendar();
    	kalendar.setTime(poruka.getVreme());
    	try {
			this.vreme = DatatypeFactory.newInstance().newXMLGregorianCalendar(kalendar);
		} catch (DatatypeConfigurationException e) {
			e.printStackTrace();
		}
    	this.sadrzaj = poruka.getSadrzaj();
    	this.korisnikId = poruka.getKorisnikId();
    	this.agentId = poruka.getAgentId();
	}

	/**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the vreme property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVreme() {
        return vreme;
    }

    /**
     * Sets the value of the vreme property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVreme(XMLGregorianCalendar value) {
        this.vreme = value;
    }

    /**
     * Gets the value of the sadrzaj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSadrzaj() {
        return sadrzaj;
    }

    /**
     * Sets the value of the sadrzaj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSadrzaj(String value) {
        this.sadrzaj = value;
    }

    /**
     * Gets the value of the korisnikId property.
     * 
     */
    public long getKorisnikId() {
        return korisnikId;
    }

    /**
     * Sets the value of the korisnikId property.
     * 
     */
    public void setKorisnikId(long value) {
        this.korisnikId = value;
    }

    /**
     * Gets the value of the agentId property.
     * 
     */
    public long getAgentId() {
        return agentId;
    }

    /**
     * Sets the value of the agentId property.
     * 
     */
    public void setAgentId(long value) {
        this.agentId = value;
    }

	public static Collection<? extends PorukaDTO> transformisi(List<Poruka> poruke) {
		List<PorukaDTO> rezultat = new ArrayList<PorukaDTO>();
		for(Poruka poruka : poruke) {
			rezultat.add(new PorukaDTO(poruka));
		}
		return rezultat;
	}

}
