//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 


package com.megatravel.utisakservice.soap.dto;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.megatravel.utisakservice.model.Utisak;


/**
 * <p>Java class for UtisakDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UtisakDTO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="komentar" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="komentarOdobren" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ocena" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="rezervacijaId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UtisakDTO", propOrder = {
    "id",
    "komentar",
    "komentarOdobren",
    "ocena",
    "rezervacijaId"
})
public class UtisakDTO {

    protected long id;
    @XmlElement(required = true)
    protected String komentar;
    protected boolean komentarOdobren;
    protected int ocena;
    protected long rezervacijaId;

    public UtisakDTO() { }
    
    public UtisakDTO(Utisak utisak) {
    	this.id = utisak.getId();
    	this.komentar = utisak.getKomentar();
    	this.komentarOdobren = utisak.isKomentarOdobren();
    	this.ocena = utisak.getOcena();
    	this.rezervacijaId = utisak.getRezervacijaId();
	}

	/**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the komentar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKomentar() {
        return komentar;
    }

    /**
     * Sets the value of the komentar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKomentar(String value) {
        this.komentar = value;
    }

    /**
     * Gets the value of the komentarOdobren property.
     * 
     */
    public boolean isKomentarOdobren() {
        return komentarOdobren;
    }

    /**
     * Sets the value of the komentarOdobren property.
     * 
     */
    public void setKomentarOdobren(boolean value) {
        this.komentarOdobren = value;
    }

    /**
     * Gets the value of the ocena property.
     * 
     */
    public int getOcena() {
        return ocena;
    }

    /**
     * Sets the value of the ocena property.
     * 
     */
    public void setOcena(int value) {
        this.ocena = value;
    }

    /**
     * Gets the value of the rezervacijaId property.
     * 
     */
    public long getRezervacijaId() {
        return rezervacijaId;
    }

    /**
     * Sets the value of the rezervacijaId property.
     * 
     */
    public void setRezervacijaId(long value) {
        this.rezervacijaId = value;
    }

	public static List<UtisakDTO> transformisi(List<Utisak> utisci) {
		List<UtisakDTO> rezultat = new ArrayList<UtisakDTO>();
		for(Utisak utisak : utisci) {
			rezultat.add(new UtisakDTO(utisak));
		}
		return rezultat;
	}

}
