server:
  port: 8762
spring:
  application:
    name: zuul-server
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  host:
    socket-timeout-millis: 600000
  sensitiveHeaders: Cookie, Set-Cookie